# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Schaake on Software
email: mark.schaake@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love Scala, and am starting to get more passionate about functional programming.
  This is where I plan to post Scala-related thoughts and experiences as I continue
  down my path.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://markschaake.github.io" # the base hostname & protocol for your site
twitter_username: markschaake
github_username:  markschaake

# Build settings
markdown: kramdown

kramdown:
  input: GFM
